name: 'Portfolio listing'
help: "New <i>Portfolio listing</i> content is created automatically.<br>\r\nYou can, however, re-save existing Portfolio listing content to update its path when needed."
description: 'An automatic page that is created in a sub-site group when portfolio content is created in the group. Always named Portfolios.'
