name: 'Opportunity for participation'
description: 'For presenting current participation opportunities for residents and other customer groups. Saved in the review mode, separate approval procedure in use.'
help: ''
