name: 'Basic content page'
description: 'The most common content type for page content. Especially for presenting services and in cases where there is no reason to use any other content type.'
help: ''
