_core:
  default_config_hash: NWpL551DTojvfvKJOZjBTPGfC9rGIQN7CGgI51a-Cao
langcode: fi
webreader_url: 'https://cdn-eu.readspeaker.com/script/8380/webReader/webReader.js?pids=wr&skin=rsbtn-tampere'
cdn_region: eu
rsConf:
  general:
    confirmPolicy: ''
    cookieLifetime: 360000000
    cookieName: ReadSpeakerSettings
    customTransLangs:
      - ar_ar
      - da_dk
      - de_de
      - el_gr
      - en
      - es_es
      - fi_fi
      - fr_fr
      - hu_hu
      - id_id
      - it_it
      - ja_jp
      - ko_kr
      - lv_lv
      - nl_nl
      - no_nb
      - pl_pl
      - pt_br
      - pt_pt
      - ro_ro
      - ru_ru
      - sv_se
      - th_th
      - tr_tr
      - uk_ua
      - vi_vn
      - zh_cn
    defaultSpeedValue: 100
    domain: readspeaker.com
    nativeLanguages: false
    popupCloseTime: 2000
    shadowDomSelector: null
    subdomain: app
    syncContainer: default
    saveLangVoice: false
    translatedDisclaimer: false
    skipHiddenContent: false
    labels:
      ignoreSelector: ''
    usePost: true
  settings:
    hl: wordsent
    hlicon: iconon
    hlscroll: scrolloff
    hlsent: '#beffd6'
    hlspeed: medium
    hltext: '#000000'
    hltoggle: hlon
    hlword: '#a4cbff'
    kb:
      clicklisten: shift+KeyH
      controlpanel: shift+KeyC
      dictionary: shift+KeyW
      download: shift+KeyD
      enlarge: shift+KeyE
      fontsizeminus: shift+Slash
      fontsizeplus: shift+Minus
      formreading: shift+KeyF
      help: shift+KeyI
      menu: shift+Digit1
      pagemask: shift+KeyM
      pause: shift+KeyP
      play: shift+KeyL
      playerfocus: shift+KeyK
      settings: shift+KeyS
      stop: shift+KeyX
      textmode: shift+KeyV
      translation: shift+KeyT
      readingvoice: shift+KeyR
      detachfocus: shift+KeyU
  ui:
    mobileVertPos: bottom=40
    controlpanel:
      vertical: bottom
      horizontal: right
    tools:
      settings: true
      voicesettings: false
      clicklisten: true
      enlarge: true
      formreading: false
      textmode: true
      pagemask: true
      download: true
      help: true
      dictionary: false
      translation: true
      skipbuttons: true
      speedbutton: true
lang: fi_fi
voice: ''
customerid: '8380'
